# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f462d9fdcdcb9b88026c165353cd0f3f778b4b6f8f4bcfc8301c3dabbb18be792f45f1c88408a85e86eeb465ba0f3df10a83dc4e061a67dc376d24aeb258a9b

test:
  secret_key_base: 457daf5598d51f2c1e30931dab4d75180338453572de9618ee613947bb4a5569c9294bf2fd4783f50dd6e3c2a087b1fe666d6cc707514b47478a88dca0f438f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
